### ISSUE TITLE
NoSuchMethodError: org.fusesource.jansi.Ansi.fgGreen()Lorg/fusesource/jansi/Ans

### ISSUE THREAD

**Issue by bartoszwalacik** [radarsh/gradle-test-logger-plugin#116]
Hi, I tried to used the plugin by applying:

```
plugins {
...
    id 'com.adarshr.test-logger' version '1.6.0'
}
```

when I run `./gradlew test`

the build crashes with this exception

```
Caused by: java.lang.NoSuchMethodError: org.fusesource.jansi.Ansi.fgGreen()Lorg/fusesource/jansi/Ansi;
        at com.adarshr.gradle.testlogger.renderer.RenderingContext$__clinit__closure8.doCall(RenderingContext.groovy:20)
        at jdk.internal.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
```

my  ./gradlew --version

```
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10 ("Oracle Corporation" 10+46)
OS:           Mac OS X 10.14.3 x86_64
```

**Comment by radarsh** [comment]
That's really odd. Can you do me a favour and checkout this [test repo on branch bugfix/issue-116](https://github.com/radarsh/gradle-test-logger-plugin-test/tree/bugfix/issue-116) and try in your environment? It is a somewhat sandboxed test project and will help me understand why it may be failing for you. If you are able to run the test successfully, you should expect to see the below output:

```
➜  gradle-test-logger-plugin-test git:(bugfix/issue-116) ./gradlew clean build

> Task :test FAILED

  com.adarshr.gradle.test.FirstSpec

    ✔ this test should pass
    ✘ this test should fail

      Condition not satisfied:

      1 == 2
        |
        false
          at com.adarshr.gradle.test.FirstSpec.this test should fail(FirstSpec.groovy:41)

    - this test should be skipped

  1 passing (1.2s)
  1 pending
  1 failing


3 tests completed, 1 failed, 1 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/c19306a/Workspace/gradle-test-logger-plugin-test/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
4 actionable tasks: 4 executed
```

**Comment by bartoszwalacik** [comment]
Well, in this test project, the plugin seems to work. I will try to use the plugin in [Javers](https://github.com/javers/javers/) and send you a feedback.

**Comment by bartoszwalacik** [comment]
In Javers, the plugin works, so I'm closing the issue, thanks!

**Comment by radarsh** [comment]
If you still get this error, it might be worth analysing the output of `./gradlew buildEnvironment` to see if you have multiple versions of Jansi on build classpath.

**Comment by bartoszwalacik** [comment]
In Javers, it works nice, see
https://github.com/javers/javers/commit/7cb838f988fa05fd010554f26048d7651dd781eb
thanks.
