### ISSUE TITLE
Stack trace does not show application code

### ISSUE THREAD

**Issue by WonderCsabo** [radarsh/gradle-test-logger-plugin#170]
**Description**

For this full stack trace:
```
  kotlin.UninitializedPropertyAccessException: lateinit property phoneNumberUtilInstance has not been initialized
      at my.app.common.util.PhoneNumberUtil.parse(PhoneNumberUtil.kt:73)
      at my.app.common.util.PhoneNumberUtil.normalizePhoneNumber(PhoneNumberUtil.kt:93)
      at my.app.common.util.PhoneNumberUtilTest.Phone number with International long format normalized correctly(PhoneNumberUtilTest.kt:51)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
      at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
      at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
      at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
      at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
      at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
      at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
      at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
```
Only this is printed from the stacktrace:
```
  kotlin.UninitializedPropertyAccessException: lateinit property phoneNumberUtilInstance has not been initialized
      at my.app.common.util.PhoneNumberUtilTest.Phone number with International long format normalized correctly(PhoneNumberUtilTest.kt:51)
```
We cannot see what is actually failing in the application!

The expected filtering should be this:
```
  kotlin.UninitializedPropertyAccessException: lateinit property phoneNumberUtilInstance has not been initialized
      at my.app.common.util.PhoneNumberUtil.parse(PhoneNumberUtil.kt:73)
      at my.app.common.util.PhoneNumberUtil.normalizePhoneNumber(PhoneNumberUtil.kt:93)
      at my.app.common.util.PhoneNumberUtilTest.Phone number with International long format normalized correctly(PhoneNumberUtilTest.kt:51)
```

**Versions**

- Test logger version: 2.1.0
- Gradle version: 6.3
- Java version: 1.8.0_242

**Type of test being run**

Junit

**Test logger configuration**

Default config

**Comment by radarsh** [comment]
Have you tried setting `showFullStackTraces` to true? It's disabled by default.

**Comment by WonderCsabo** [comment]
Yep, that is how i obtained the full stacktrace. However the full stacktrace is really not needed, only the test method and above. But the filtering only shows the test method line, and filters out everything above. I do not think that was intentional.

**Comment by radarsh** [comment]
@WonderCsabo It is indeed intentional. In fact, this plugin tries to emulate the [behaviour of Gradle when `testLogging.exceptionFormat` is equal to `short`](https://github.com/gradle/gradle/blob/master/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/logging/ShortExceptionFormatter.java#L54) (the default value).

### Plugin output when `showFullStackTraces = false`

```
  com.adarshr.gradle.testlogger.theme.ThemeFactorySpec

    ✘ console type of plain overrides any theme configuration (2.2s)

      java.lang.ArithmeticException: Division by zero
          at com.adarshr.gradle.testlogger.theme.ThemeFactorySpec.console type of plain overrides any theme configuration(ThemeFactorySpec.groovy:47)
``` 

### Gradle output without the plugin applied when `testLogging.exceptionFormat = 'short'` (default)

```
com.adarshr.gradle.testlogger.theme.ThemeFactorySpec > console type of plain overrides any theme configuration FAILED
    java.lang.ArithmeticException at ThemeFactorySpec.groovy:47
```

### Gradle output without the plugin applied when `testLogging.exceptionFormat = 'full'`

```
com.adarshr.gradle.testlogger.theme.ThemeFactorySpec > console type of plain overrides any theme configuration FAILED
    java.lang.ArithmeticException: Division by zero
        at java.math.BigDecimal.divide(BigDecimal.java:1742)
        at com.adarshr.gradle.testlogger.theme.ThemeFactory.resolveThemeType(ThemeFactory.groovy:24)
        at com.adarshr.gradle.testlogger.theme.ThemeFactory.getTheme(ThemeFactory.groovy:17)
        at com.adarshr.gradle.testlogger.theme.ThemeFactorySpec.console type of plain overrides any theme configuration(ThemeFactorySpec.groovy:47)
```

### Plugin output when `showFullStackTraces = true`

```
  com.adarshr.gradle.testlogger.theme.ThemeFactorySpec

    ✘ console type of plain overrides any theme configuration (2.1s)

      java.lang.ArithmeticException: Division by zero
          at java.math.BigDecimal.divide(BigDecimal.java:1742)
          at com.adarshr.gradle.testlogger.theme.ThemeFactory.resolveThemeType(ThemeFactory.groovy:24)
          at com.adarshr.gradle.testlogger.theme.ThemeFactory.getTheme(ThemeFactory.groovy:17)
          at com.adarshr.gradle.testlogger.theme.ThemeFactorySpec.console type of plain overrides any theme configuration(ThemeFactorySpec.groovy:47)
```

Now, whether we should change this behaviour or not needs to be carefully considered as it will end up producing longer stack traces all the time.

**Comment by radarsh** [comment]
In the spirit of having least surprises when switching to this plugin from native Gradle behaviour I have decided to leave the existing behaviour in.
