### ISSUE TITLE
Support Configuration Cache

### ISSUE THREAD

**Issue by Goooler** [radarsh/gradle-test-logger-plugin#327]
**Description**

1. Enable CC for this project, we can see:
```
rg.gradle.api.GradleException: Could not load the value of field `subscribedListeners` of `org.gradle.api.tasks.testing.AbstractTestTask$BroadcastSubscriptions` bean found in field `testListenerSubscriptions` of task `:functionalTest` of type `org.gradle.api.tasks.testing.Test`.	
at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:112)	
at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt$readPropertyValue$1.invokeSuspend(BeanPropertyReader.kt)	
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	
at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)	
at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$$inlined$Continuation$1.resumeWith(Continuation.kt:167)	
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)	
at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
```

Build scan: https://scans.gradle.com/s/fojpmsyvoqbks/failure?expanded-stacktrace=WyIwIl0#1

2. Enable CC for all functional tests, we can see:

```
1 problem was found storing the configuration cache.	
- Gradle runtime: support for using a Java agent with TestKit builds is not yet implemented with the configuration cache.	
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:not_yet_implemented:testkit_build_with_java_agent
```
Build scan: https://scans.gradle.com/s/ibcfhqf4roxyw/tests/overview?outcome=FAILED

Repro: https://github.com/Goooler/gradle-test-logger-plugin/pull/30

**Versions**

- Test logger version: 4.0.0
- Gradle version: 8.4

**Type of test being run**

Whether it is JUnit, Spock, TestNg, or anything else. Also, try to include a sample test here.

**Test logger configuration**

Paste your test logger configuration here.

**Screenshots**

If possible, add screenshots to help explain your problem.

**Additional information**

Add any other information about the problem here.

**Comment by Goooler** [comment]
Links #163.
